### ISSUE TITLE
Could use better instructions

### ISSUE THREAD

**Issue by TonyBShepherd** [sumeshi/sumeshi.github.io#19]
Lost a Win10 install on SSD (1T). Used Knoppix dd to copy full image to USB3 disk. Thought I could use ntfsdump/ntfsfind to get my files back. Software doesn't work "out of the box" on Win8.1 system. I don't know Python, Linux, C++. Spent about a day trying to get everything to work - gave up. Dependencies on pytsk3/sluethkit (and others) mentioned only in "license" of README file. Would have been nice to know software was not a "download and use" package. I appreciate your efforts - wish I could have learned how to try it. Thank you.

**Comment by sumeshi** [comment]
Thank you for your input. I apologize for not being able to help you.

Originally, ntfsfind/ntfsdump was one of my attempts to simplify and automate the process with a minimalist program after getting tired of GUI applications like Autopsy/FTK Imager.

I realize that a proper description is needed, but it is inadequate for now.
I will continue to develop and update the software. Thank you.

**Comment by TonyBShepherd** [comment]
Thank you for your reply. I still haven't recovered my files but I am developing a program that may be helpful to others. (I hope) it will work by extracting files from the full disk image created using Knoppix. Once I get my files back I'd be happy to share the (Free Pascal 3.2.0) source code with others. Thanks again for your reply. Happy Holidays!
